
CASE_WIDTH   = 1 # taille d'une case (2.5cm en vrai)
CASE_WIDTH_2 = CASE_WIDTH / 2

BRAS_LENGTH   = CASE_WIDTH * 8
BRAS_LENGTH_2 = BRAS_LENGTH / 2 
BRAS_WIDTH    = CASE_WIDTH_2
BRAS_WIDTH_2  = BRAS_WIDTH / 2

PION_Z_MINI = CASE_WIDTH_2
PION_Z_MAXI = CASE_WIDTH * 2

POS_BRAS_INIT_X = - CASE_WIDTH * 2
POS_BRAS_INIT_Y = CASE_WIDTH * 10 + CASE_WIDTH * 2
POS_BRAS_INIT_Z = 0

POS_BRAS_REPOS_X = 0
POS_BRAS_REPOS_Y = CASE_WIDTH * 10
POS_BRAS_REPOS_Z = PION_Z_MINI 

WEBCAM_POS_X = CASE_WIDTH*5
WEBCAM_POS_Y = CASE_WIDTH*10 + CASE_WIDTH * 5 # 20 cm en vrai
WEBCAM_POS_Z = CASE_WIDTH*8  # 35 cm en vrai
WEBCAM_TIGE_LENGTH = WEBCAM_POS_Z
WEBCAM_TIGE_LENGTH_2 = WEBCAM_TIGE_LENGTH / 2

ROUGE = (1, 0, 0, 1)
VERT  = (0, 1, 0, 1)
BLEU  = (0, 0, 1, 1)
NOIR  = (0, 0, 0, 1)
BLANC = (1, 1, 1, 1)

DUREE_ANIM = 2.0 # en secondes

PIECES_PERDUES_X = -CASE_WIDTH
PIECES_PERDUES_Y = CASE_WIDTH * 0.6
PIECES_PERDUES_SPACING = CASE_WIDTH * 0.7
PIECES_PERDUES_PAR_COLONNE = 10
